In [12]:
import torch

In [13]:
a = torch.tensor(2.0, requires_grad= True)
b = torch.tensor(3.0, requires_grad= True)
x = torch.tensor(4.0, requires_grad = True)

In [14]:
y = a + b

In [15]:
z = x * y

In [16]:
z

tensor(20., grad_fn=<MulBackward0>)

In [17]:
y.grad_fn

In [18]:
scores = torch.tensor([10., 20., 30.])

In [19]:
N = 10

D_in = 1
D_out = 1

X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)

y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

In [20]:
W = torch.randn(D_in, D_out, requires_grad= True)
b = torch.randn(1, requires_grad= True)

W, b

(tensor([[1.0649]], requires_grad=True), tensor([1.1475], requires_grad=True))

In [21]:
y_hat = X @ W + b

In [22]:
y_hat

tensor([[ 6.6287e-01],
        [ 1.5379e+00],
        [ 2.9324e+00],
        [ 9.5781e-01],
        [ 1.4687e+00],
        [ 3.1324e+00],
        [ 3.2256e+00],
        [ 1.9930e+00],
        [-6.1056e-01],
        [-2.9569e-03]], grad_fn=<AddBackward0>)

In [23]:
y_true

tensor([[ 0.0082],
        [ 1.9183],
        [ 4.2902],
        [ 0.8094],
        [ 1.5905],
        [ 4.7544],
        [ 5.0511],
        [ 2.4344],
        [-2.3793],
        [-1.0495]])

In [24]:
error = y_hat - y_true
squared_error = error ** 2
loss = squared_error.mean()

loss

tensor(1.2836, grad_fn=<MeanBackward0>)

In [25]:
loss.backward()

In [26]:
W.grad

tensor([[-2.7527]])

In [27]:
b.grad

tensor([-0.4261])

In [28]:
import torch

In [29]:
 learning_rate, epochs = 0.01, 100
 W, b = torch.randn(1,1, requires_grad= True), torch.randn(1, requires_grad= True)

In [30]:
y_hat = X @ W + b
loss = torch.mean((y_hat - y_true) ** 2)
loss.backward()

In [31]:
with torch.no_grad():
  W -= learning_rate * W.grad
  b -= learning_rate * b.grad

W.grad.zero_(); b.grad.zero_()

tensor([0.])

In [32]:
for epoch in range(epochs):
  y_hat = X @ W + b
  loss = torch.mean((y_hat - y_true) ** 2)
  loss.backward()

  with torch.no_grad():
    W -= learning_rate * W.grad
    b -= learning_rate * b.grad

  W.grad.zero_(); b.grad.zero_()

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Loss: {loss}")

Epoch: 0 | Loss: 9.393960952758789
Epoch: 10 | Loss: 4.7712931632995605
Epoch: 20 | Loss: 2.4370367527008057
Epoch: 30 | Loss: 1.2553638219833374
Epoch: 40 | Loss: 0.6550399661064148
Epoch: 50 | Loss: 0.3485402464866638
Epoch: 60 | Loss: 0.19097492098808289
Epoch: 70 | Loss: 0.10920938104391098
Epoch: 80 | Loss: 0.06624113023281097
Epoch: 90 | Loss: 0.04328678920865059
